# yazi.toml
[manager]
show_hidden = true

[plugin]
prepend_previewers = [
    { mime = "{image,audio,video}/*", run = "mediainfo"},
    { mime = "application/x-subrip", run = "mediainfo"},
    { mime = "audio/*",   run = "exifaudio"},
    { mime = "text/csv", run = "miller"},
]
